= Hypermedia with Spring Hateoas (Sandbox)

Little Sandbox to play around with Spring Hateoas.

**Features:**

* Hypermedia
** link:https://rwcbook.github.io/hal-forms/[HAL-FORMS], not just plain link:https://datatracker.ietf.org/doc/html/draft-kelly-json-hal-08[HAL (Hypertext Application Language)]
** Pagination with `previous` and `next` relations
** link:https://datatracker.ietf.org/doc/html/rfc6570[URI Templates] like `/owners{?limit,offspring}`
* Spring Hateoas
** inkl. link:https://docs.spring.io/spring-hateoas/docs/1.2.2/reference/html/#mediatypes.hal.curie-provider[CURIEs (Compact URIs)] which are used to scope custom **rel**s because they are not registered link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[IANA link relation types].
* link:https://github.com/toedter/hal-explorer[Hal-Explorer] (after starting the backend visit http://localhost:8080)

== Getting started

. Use the link:.sdkmanrc[.sdkmanrc] java version: `sdk env use`
. Start the backend: `./gradlew run`
. Explore via curl or httpie

Or at your own leasure:

* Run tests: `./gradlew test`

== Explore

NOTE: All Controller methods are explicitly annotated with `produces = ["application/prs.hal-forms+json"]`, otherwise the server only answers with hal-forms if the client understands it, leaving you wondering where `"_templates": [...]` is in your json response.

The root gives us information where we can reach other items.

.http GET localhost:8080/accounts/
[source,json]
----
{
    {
        "_embedded": {
            "accountDtoes": [
                {
                    "_id": "1",
                    "_links": {
                        "self": {
                            "href": "http://localhost:8080/accounts/1"
                        }
                    },
                    "balance": 1,
                    "name": "one"
                }
            ]
        }
    }
}
----

Notice that when we withdraw 9 credits we still have the option to withdraw more, but should the balance go to zero we can no longer withdraw and only deposit.
Affordances at work :)

.http POST localhost:8080/accounts/1/withdraw amount=9
[source,json]
----
{
    "balance": 1,
    "name": "one",
    "_templates": {
        "default": {
            "method": "POST",
            "properties": [
                {
                    "name": "amount",
                    "readOnly": true,
                    "type": "number"
                }
            ],
            "target": "http://localhost:8080/accounts/1/withdraw"
        },
        "deposit": {
            "method": "POST",
            "properties": [
                {
                    "name": "amount",
                    "readOnly": true,
                    "type": "number"
                }
            ],
            "target": "http://localhost:8080/accounts/1/deposit"
        }
    }
}
----

== Further Reading

* link:https://github.com/spring-projects/spring-hateoas-examples/tree/main/affordances[Spring Hateoas Affordances Examples]